map_config:
  heatmap_num: 3
  legend_num: 3
  heatmap_1:
    raw_data: FALSE
    kmer_col: 1
    kmer_row: 1
    split_row_name: NULL
    percentage: 0.4
    kmer_col_color: NULL
    kmer_row_color: "pool_col"
    dendrogram: "both"
    Rowv: TRUE
    Colv: TRUE
    color_theme: "gradient_col_gr"
    distfun: "dist"
    hclustfun: "hclust"
  heatmap_2:
    raw_data: TRUE
    split_row_name: NULL
    percentage: 0.1
    dendrogram: "both"
    Colv: TRUE
    Rowv: FALSE
    color_theme: "gradient_col_op"
    distfun: "dist"
    hclustfun: "hclust" 
  heatmap_3:
    percentage: 0.1
  legend_1:
    - ["Gender","binary_col", 3]
    - ["Age", "binary_col", 2]
    - ["Fusion", "tag_col", 4]
    - ["other_fusion", "pool_col", 5]
  legend_2:
    - ["KRAS", "mutation_col", 6]
    - ["P53", "mutation_col", 7]
    - ["NRAS", "mutation_col", 8]
  legend_3:
    - ["Gene_1_exp", "gradient_col_op", 9]
    - ["Gene_2_exp", "gradient_col_br", 10]
  map_order:
    - "heatmap_1"
    - "legend_1"
    - "heatmap_2"
    - "heatmap_3"
    - "legend_2"
    - "legend_3"
  split_sample: 
    - "M1003"
    - "M4002"

color_config:
  bg_col: "#EEEEEE"
  tag_col: "#696969"
  binary_col: ["#196ABD", "#C20B01"]
  white_col: "#FFFFFF"
  black_col: "#000000"
  mutation_col:
    missense: "#3987CC"
    frameshift: "#DB3D3D"
    nonsense: "#FF7F0E"
    protein_del: "#7F7F7F"
    protein_ins: "#8C564B"
    one_hit: "#819981"
    tow_hit: "#499E49"
    three_hit: "#237023"
  pool_col: ["#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#A6CEE3", "#1F78B4", "#B2DF8A", "#33A02C", "#FB9A99", "#E31A1C", "#FDBF6F", "#FF7F00", "#CAB2D6", "#6A3D9A"]
  gradient_col_gr: ["green", "black", "red"]
  gradient_col_yp: ["yellow", "black", "purple"]
  gradient_col_op: ["orange", "white", "purple"]
  gradient_col_br: ["blue", "red"]
  gv_line_col: "#FDBF6F"
  gv_bar_col: "#E6AB02"
  gv_dot_col: "#000000"
  kmer_col: ["green", "blue", "red"]



